spring:
  datasource:
    redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        #最大连接数
        max-active: 8
        #最大阻塞等待时间(负数表示没限制)
        max-wait: -1
        #最大空闲
        max-idle: 8
        #最小空闲
        min-idle: 0
        #连接超时时间
        timeout: 10000
shiro:
  filter:
    chain:
      #true开启拦截，false关闭拦截
      enabled: true
      definitions: /login = anon
jwt:
  secret: adsfadfdsfd
  expire: 60000
wx:
  miniapp:
    configs:
      - appid: wxacf4177bc9ff6ee9
        secret: 8891c37ad1862b2952541f6d4eba104e
        token: Uel9QcFVjI3DnV3isbE3Pu0kIGKCvQ
        aesKey: zLt0JF9WHbZqORxGbWQE35MTzWxT42zu0xkfrB36lv2
        msgDataFormat: JSON
task:
  enabled: true
logging:
  config: classpath:logback-dev.xml
  file:
    path: D:\my_project\project\tool-box-cloud\logs\tool-box-api-logs\