server:
  port: 19888
  servlet:
    context-path: /task

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    # 服务名
    name: tool-box-task
  profiles:
    active: dev
  config:
    import:
      - optional:nacos:${spring.application.name}-${spring.profiles.active}.yml
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
        namespace: a48fbc8e-8558-4383-be24-5d70c0a62869
        group: ${nacos_discovery_group}
      config:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
        namespace: a48fbc8e-8558-4383-be24-5d70c0a62869
        group: TOOL_BOX_TASK_GROUP
        file-extension: yaml
        refresh-enabled: true
